<<<<<<< HEAD
#检测的时间间隔(单位分钟)
intervalTime=5
omniuser="fuzamei"
omnipasswd="fuzamei"
noderpcuser="fuzamei"
noderpcpasswd="fuzamei"
fromEmail="fuzamei@126.com"
fromEmailPsw="fzm123456"
toEmail="714765233@qq.com"

#bty平行链币的名称
parallel="DTC,TESTC"

[ratelimit]
#是否开启限流
limitOpen=true
#同时处理的最大请求数量，0表示不限制
maxConCurrentNum=2
#按ip过滤时间间隔（单位秒）
timeInterval=60
#在时间间隔内最大访问次数
maxCount=10

[log]
loglevel="debug"
logConsoleLevel="info"
logFile="logfiles/monitor.log"


[mysql]
mysqlIp="rm-bp1fs8x9x07bz83qbwo.mysql.rds.aliyuncs.com"
mysqlPort=3306
mysqlPwd="Q9ya9BRymh3sFHbt"
#mysqlIp="182.61.42.81"
#mysqlPort=3306
#mysqlPwd="123456"

#数据库名称
dbName="monitor"
#表名 要检查端口号是否正常的服务器表
nodePortTable="nodePortInfo"
#表名 要检查节点同步高度的服务器表
nodeSyncTable="nodeSyncInfo"
=======
ipPosts=["45.106.116.142:8801","47.116.117.143:8802"]
intervalTime=1

fromEmail="fuzamei@126.com"
fromEmailPsw="授权码"
toEmail="yqm@disanbo.com,2355241170@qq.com"
sendTime=10
>>>>>>> 43b7f57b001bf47c96bca9ea10c9a48e391176fb
